#!/usr/bin/env bash
# Assemble a self-contained aideck-gap8-examples app dir for one model, so it can
# be built with the SAME docker + `make` flow that built the wifi-img-streamer.
# Reads the model's 1-in/6-out int8 byte counts from its ONNX (feeding AT_*_BYTES;
# a wrong count would let the CNN write out of bounds). No `set -e`: a fit/codegen
# failure is a RESULT to record (LUT/Stage-0 discipline), not a script error.
#
#   mcu/board/build_bench.sh cand_a5fddcc354bd 192
#   mcu/board/build_bench.sh yolo11n_pose_160_raw 160 160000 8192   # L2, stack overrides
set -uo pipefail

MODEL="${1:?usage: build_bench.sh <model> <res> [L2] [stack]}"
RES="${2:?need res}"
L2="${3:-84000}"
STACK="${4:-8192}"

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
EX_ROOT="${AIDECK_EXAMPLES:-$HOME/aideck-gap8-examples}"
SRC="${REPO}/mcu/board/net_bench"
ONNX="${REPO}/models/res${RES}/${MODEL}.onnx"
CALIB="${REPO}/data/mcu/probes/aq_sample"
NAS_PY="${REPO}/.venv-nas/bin/python"
APPDIR="${EX_ROOT}/examples/ai/net-bench-${MODEL}"

[[ -f "${ONNX}" ]] || { echo "NO ONNX: ${ONNX}"; exit 2; }
[[ -d "${EX_ROOT}/examples/ai/classification" ]] || { echo "NO aideck examples at ${EX_ROOT}"; exit 2; }
compgen -G "${CALIB}/*.jpg" >/dev/null || { echo "NO calib jpgs at ${CALIB}"; exit 2; }

# 1-input + 6-output int8 byte counts from the ONNX (int8 -> numel == bytes).
read -r IN O1 O2 O3 O4 O5 O6 < <("${NAS_PY}" - "${ONNX}" <<'PY'
import sys, onnx
m = onnx.load(sys.argv[1], load_external_data=False)
def numel(t):
    n = 1
    for d in t.type.tensor_type.shape.dim:
        n *= (d.dim_value or 0)
    return n
vals = [numel(m.graph.input[0])] + [numel(o) for o in m.graph.output]
assert len(vals) == 7, f"expected 1 input + 6 outputs, got {len(vals)-1} outputs"
print(*vals)
PY
) || { echo "IO_READ_FAIL ${MODEL} (need .venv-nas with onnx)"; exit 3; }
echo "IO in=${IN} out=$((O1+O2+O3+O4+O5+O6)) B  (6 outputs: ${O1} ${O2} ${O3} ${O4} ${O5} ${O6})"

# Assemble the self-contained app dir.
rm -rf "${APPDIR}"
mkdir -p "${APPDIR}/model" "${APPDIR}/aq_sample"
cp "${SRC}/net_bench.c" "${SRC}/Makefile" "${APPDIR}/"
cp "${EX_ROOT}/examples/ai/classification/model_decl.mk" \
   "${EX_ROOT}/examples/ai/classification/model_rules.mk" \
   "${EX_ROOT}/examples/ai/classification/config.ini" "${APPDIR}/"
cp "${ONNX}" "${APPDIR}/${MODEL}.onnx"
cp "${CALIB}"/*.jpg "${APPDIR}/aq_sample/"
sed "s/@RES@/${RES}/g" "${SRC}/nntool_script.tmpl" > "${APPDIR}/model/nntool_script"

# Per-model make config the Makefile include's.
cat > "${APPDIR}/model_config.mk" <<EOF
# generated by mcu/board/build_bench.sh -- do not edit
ONNX = 1
MODEL_PREFIX = ${MODEL}
TRAINED_MODEL = \$(CURDIR)/${MODEL}.onnx
NNTOOL_SCRIPT = model/nntool_script
MODEL_L2_MEMORY = ${L2}
CLUSTER_STACK_SIZE = ${STACK}
BENCH_MODEL_CFLAGS = -DAT_INPUT_BYTES=${IN} \\
  -DAT_OUT1_BYTES=${O1} -DAT_OUT2_BYTES=${O2} -DAT_OUT3_BYTES=${O3} \\
  -DAT_OUT4_BYTES=${O4} -DAT_OUT5_BYTES=${O5} -DAT_OUT6_BYTES=${O6} \\
  -DAT_MODEL_RES=${RES}
EOF

echo
echo "ASSEMBLED  ${APPDIR}"
echo "Build it in the Bitcraze toolchain docker (the one that built the streamer):"
echo "    cd examples/ai/net-bench-${MODEL} && make clean model all image"
echo "Flashable image will be at:"
echo "    ${APPDIR}/BUILD/GAP8_V2/GCC_RISCV_FREERTOS/target.board.devices.flash.img"
